apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-de-eventos-deployment
spec:
  # Qtas replicas 
  replicas: 1
  selector:
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata:
      labels:
        app: barramento-de-eventos
    spec:
      containers:
        - name: barramento-de-eventos # '-' é uma coleção
          image: mmarins14/ecm516-barramento-de-eventos # nada ou latest significa que vou pegar a ultima versao
          # resources:
          #   limits:
          #     memory: 256Mi # 256 MB i -> binario
          #     cpu: 1
--- 
apiVersion: v1 
kind: Service
metadata:
  name: barramento-de-eventos-service
spec:
  selector:
    app: barramento-de-eventos
  type: ClusterIP #porta interna
  ports:
    - name: barramento-de-eventos
      protocol: TCP 
      port: 10000
      targetPort: 10000 # porta que o container esta escutando
      