apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-de-eventos-deployment
spec:
  # Qtas replicas 
  replicas: 1
  selector:
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata:
      labels:
        app: barramento-de-eventos
    spec:
      containers:
        - name: barramento-de-eventos # '-' é uma coleção
          image: mmarins14/ecm516-barramento-de-eventos # nada ou latest significa que vou pegar a ultima versao
          # resources:
          #   limits:
          #     memory: 256Mi # 256 MB i -> binario
          #     cpu: 1
