apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificacao-deployment
spec:
  # Qtas replicas 
  replicas: 1
  selector:
    matchLabels:
      app: classificacao
  template:
    metadata:
      labels:
        app: classificacao
    spec:
      containers:
        - name: classificacao # '-' é uma coleção
          image: mmarins14/ecm516-classificacao # nada ou latest significa que vou pegar a ultima versao
          # resources:
          #   limits:
          #     memory: 256Mi # 256 MB i -> binario
          #     cpu: 1
--- 
apiVersion: v1 
kind: Service
metadata:
  name: classificacao-clusterip-service
spec:
  selector:
    app: classificacao
  type: ClusterIP #porta interna
  ports:
    - name: classificacao
      protocol: TCP 
      port: 7000
      targetPort: 7000 # porta que o container esta escutando
--- 
apiVersion: v1
kind: Service
metadata:
  name: classificacao-service
spec:
  #Porta externa, acessivel fora do cluster kubernets
  type: NodePort
  # Porta interna, acessivel dentro do cluster kubernets
  selector:
    app: classificacao
  ports: 
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000 #porta do microservico