apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-deployment
spec:
  # Qtas replicas 
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
        - name: consulta # '-' é uma coleção
          image: mmarins14/ecm516-consulta # nada ou latest significa que vou pegar a ultima versao
          # resources:
          #   limits:
          #     memory: 256Mi # 256 MB i -> binario
          #     cpu: 1
--- 
apiVersion: v1 
kind: Service
metadata:
  name: consulta-clusterip-service
spec:
  selector:
    app: consulta
  type: ClusterIP #porta interna
  ports:
    - name: consulta
      protocol: TCP 
      port: 6000
      targetPort: 6000 # porta que o container esta escutando
--- 
apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  #Porta externa, acessivel fora do cluster kubernets
  type: NodePort
  # Porta interna, acessivel dentro do cluster kubernets
  selector:
    app: consulta
  ports: 
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000 #porta do microservico