apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment
spec:
  # Qtas replicas 
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes # '-' é uma coleção
          image: mmarins14/ecm516-lembretes # nada ou latest significa que vou pegar a ultima versao
          # resources:
          #   limits:
          #     memory: 256Mi # 256 MB i -> binario
          #     cpu: 1
--- 
apiVersion: v1
kind: Service
metadata:
  name: lembretes-clusterip-service
spec:
  selector:
    app: lembretes
  type: ClusterIP #porta interna
  ports:
    - name: lembretes
      protocol: TCP 
      port: 4000
      targetPort: 4000 # porta que o container esta escutando