apiVersion: v1
kind: Pod
metadata:
  name: lembretes
spec:
  containers:
  - name: lembretes
    image: mmarins14/ecm516-lembretes:0.0.1
    resources:
      limits:
        memory: 256Mi # 256 MB i -> binario
        cpu: 1