apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacao-deployment
spec:
  # Qtas replicas 
  replicas: 1
  selector:
    matchLabels:
      app: observacao
  template:
    metadata:
      labels:
        app: observacao
    spec:
      containers:
        - name: observacao # '-' é uma coleção
          image: mmarins14/ecm516-observacao # nada ou latest significa que vou pegar a ultima versao
          # resources:
          #   limits:
          #     memory: 256Mi # 256 MB i -> binario
          #     cpu: 1
--- 
apiVersion: v1 
kind: Service
metadata:
  name: observacao-clusterip-service
spec:
  selector:
    app: observacao
  type: ClusterIP #porta interna
  ports:
    - name: observacao
      protocol: TCP 
      port: 5000
      targetPort: 5000 # porta que o container esta escutando
--- 
apiVersion: v1
kind: Service
metadata:
  name: observacao-service
spec:
  #Porta externa, acessivel fora do cluster kubernets
  type: NodePort
  # Porta interna, acessivel dentro do cluster kubernets
  selector:
    app: observacao
  ports: 
    - name: observacao
      protocol: TCP
      port: 5000
      targetPort: 5000 #porta do microservico